### ISSUE TITLE
Prueba 1

### ISSUE THREAD

**Issue by nbxandresvejar** [CastilloDelgado/neubox_challenge_python#1]
Problema 1: Python
- El archivo de entrada se encuentra fijo lo que no permite realizar mayores pruebas o datos de entrada. Como práctica no se deben dejar datos en harcode.
- Aún cuando no se puede probar, revisando el código no cumple con las condiciones especificadas en el problema.

Problema 2: Python
- El archivo de entrada se encuentra fijo lo que no permite realizar mayores pruebas o datos de entrada.
- Revisar nuevamente las condiciones del problema y la forma de calcular el resultado.

**Comment by CastilloDelgado** [comment]
**Problema 1**
- Se solicita el nombre del archivo de entrada al inicio de programa para que se puedas ingresar distintos nombres pero siempre con formato .txt
- Se hace un loop para usar el programa tantas veces sean necesarias
- Se agregan condiciones para validar la información del archivo de entrada

**Problema 2**
- Se solicita el nombre del archivo de entrada al inicio de programa para que se puedas ingresar distintos nombres pero siempre con formato .txt
- Se hace un loop para usar el programa tantas veces sean necesarias
- Se agregan condiciones para validar la información del archivo de entrada

**Nota**
- Se hicieron validaciones con varios archivos de entrada, me gustaría saber cuales les han causado problemas.
